#!/bin/bash

RASPBERRY_PI_IP=$(cat raspberry_pi_IP)
cat >hosts <<EOF
[hosts]
raspberry ansible_host=${RASPBERRY_PI_IP} ansible_user=pi working_directory=/home/pi/

[hosts:vars]
ansible_python_interpreter=/usr/bin/python3
EOF
