#!/bin/bash

RASPBERRY_IP=$(cat raspberry_ip)
cat >hosts <<EOF
[hosts]
raspberry ansible_host=${RASPBERRY_IP} ansible_user=pi working_directory=/home/pi/

[hosts:vars]
ansible_python_interpreter=/usr/bin/python3
EOF
