---
- name: Copy kodi addons
  unarchive:
    src: "{{ addons_file_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ addons_location }}"
    owner: pi
    group: pi

- name: Copy kodi userdata
  unarchive:
    src: "{{ userdata_file_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ userdata_location }}"
    owner: pi
    group: pi

- name: Tweak overscan
  copy:
    src: ../../configuration/emulation-station/config.txt
    dest: /boot/config.txt
    owner: root
    group: root
